### ISSUE TITLE
I don't really understand the encryption , like how can i set it up?

### ISSUE THREAD

**Issue by ftk789** [pcarrier/gauth#49] opened 2021-07-30 15:52 UTC
I don't really understand the encryption , like how can i set it up?

**Comment by creachadair** [comment] 2021-07-30 15:55
Take a look at https://github.com/pcarrier/gauth#encryption, which shows an example of how to encrypt the `gauth.csv` file. The tool automatically detects that style of encryption, and will prompt for your passphrase before generating a code.

**Comment by ftk789** [comment] 2021-07-30 16:17
oh yea i did that but look at this #50

**Comment by creachadair** [comment] 2021-07-30 17:56
Closed as a duplicate of #50.

**Closed by creachadair** 2021-07-30 17:56 UTC
Labels: duplicate
